# makefile para compilar la secuencia con Hilos y Semaforos.

# Si se ejecuta solo 'make' 'se ejecuta el objetivo all, que incluye todo.
all: SecuenciaHS

# Compilacion del archivo principal.
SecuenciaHS:
	gcc SecuenciaHS.c -o SecuenciaHS -pthread
	
clean:
	rm -f SecuenciaHS *.o
