# makefile para compilar la secuencia con Procesos y Pipes.

# Si se ejecuta solo 'make' 'se ejecuta el objetivo all, que incluye todo.
all: SecuenciaPP

# Compilacion del archivo principal.
SecuenciaPP:
	gcc SecuenciaPP.c -o SecuenciaPP
	
clean:
	rm -f SecuenciaPP *.o
