# makefile para compilar la minishell

# Si se ejecuta solo 'make' 'se ejecuta el objetivo all, que incluye todo.
all: PlantaRecicladoPIPES

# Compilacion de la planta de reciclado.
PlantaRecicladoPIPES:
	gcc PlantaRecicladoPIPES.c -o PlantaRecicladoPIPES
	
clean:
	rm -f PlantaRecicladoPIPES *.o
